# Accumulates per-case RpcSpecResult objects and renders them into:
#   - a concise console summary (format()) printed during the test run
#   - a detailed Markdown report (report()) written to rpc_schema_report.md
# Also provides _schema_mismatches() and _expected_failure_drift() used by the
# test assertions to detect new failures or stale whitelist entries.

from collections import defaultdict

from _rpc_spec_common import _markdown_json
from _schema_constants import (
    DECIMAL_BLOCK_NUMBER_REQUEST_SCHEMA_EXCEPTIONS,
    EXCLUDED_SCHEMA_SPEC_CASES,
    SCHEMA_CATEGORY_TITLES,
    SCHEMA_MISMATCH_WHITELIST,
    UNIMPLEMENTED_RPC_METHODS,
)
from _schema_normalize import _format_schema_differences


class RpcSpecSchemaSummary:
    def __init__(self):
        self.schema_correct = []
        self.not_implemented = []
        self.request_schema_wrong = []
        self.response_schema_wrong = []

    def add(self, result):
        getattr(self, result.category).append(result)

    def format(self):
        lines = ["ethermint RPC spec schema case summary"]
        for attr in [
            "schema_correct",
            "not_implemented",
            "request_schema_wrong",
            "response_schema_wrong",
        ]:
            results = getattr(self, attr)
            lines.append(f"- {SCHEMA_CATEGORY_TITLES[attr]}: {len(results)}")
            by_method = defaultdict(int)
            examples = []
            for result in results:
                by_method[result.method] += 1
                if len(examples) < 8:
                    examples.append(result)
            if by_method:
                method_counts = ", ".join(
                    f"{method}={count}" for method, count in sorted(by_method.items())
                )
                lines.append(f"  methods: {method_counts}")
            for result in examples:
                lines.append(f"  example: {result.spec_name}: {result.reason}")
            if len(results) > len(examples):
                lines.append(f"  ... {len(results) - len(examples)} more")
        lines.extend(self._format_method_summary())
        return "\n".join(lines)

    def report(self):
        lines = [
            "# Ethermint RPC Schema Spec Report",
            "",
            "Generated by `execution-api/test_rpc_spec_schema.py`.",
            "",
            (
                "This report compares Ethermint JSON-RPC responses with the "
                "copied execution-apis `.io` fixtures by schema only. Values "
                "are ignored, but response kind, object keys, and JSON value "
                "types must match."
            ),
            "",
            "## Excluded Cases",
            "",
            (
                "These fork-specific block-number fixtures are skipped "
                "because Ethermint currently returns Prague-era block fields "
                "for historical blocks, while Geth formats each block "
                "response according to the fork active at the queried block."
            ),
            "",
        ]
        lines.extend(
            f"- `{spec_name}`" for spec_name in sorted(EXCLUDED_SCHEMA_SPEC_CASES)
        )
        lines.extend(
            [
                "",
                "## Case Summary",
                "",
            ]
        )
        lines.extend(self._markdown_case_summary())
        lines.extend(["", "## Method Summary", ""])
        lines.extend(self._markdown_method_summary())
        lines.extend(["", "## Null Result Summary", ""])
        lines.extend(self._markdown_null_result_summary())
        lines.extend(["", "## Expected Failure Whitelist", ""])
        lines.extend(self._markdown_expected_failure_whitelist())
        lines.extend(["", "## Detailed Mismatches", ""])
        lines.extend(self._markdown_details())
        return "\n".join(lines).rstrip() + "\n"

    def _markdown_case_summary(self):
        lines = ["| Category | Cases | Methods |", "| --- | ---: | --- |"]
        for attr in [
            "schema_correct",
            "not_implemented",
            "request_schema_wrong",
            "response_schema_wrong",
        ]:
            results = getattr(self, attr)
            methods = sorted({result.method for result in results})
            lines.append(
                "| {} | {} | {} |".format(
                    SCHEMA_CATEGORY_TITLES[attr],
                    len(results),
                    ", ".join(methods) if methods else "-",
                )
            )
        return lines

    def _markdown_method_summary(self):
        by_method = defaultdict(list)
        for result in self._all_results():
            by_method[result.method].append(result)

        by_verdict = defaultdict(list)
        for method, results in sorted(by_method.items()):
            by_verdict[self._method_verdict(results)].append((method, results))

        lines = ["| Category | Methods | Details |", "| --- | ---: | --- |"]
        for verdict in [
            "schema_correct",
            "not_implemented",
            "request_schema_wrong",
            "response_schema_wrong",
            "mixed_wrong",
        ]:
            methods = by_verdict.get(verdict, [])
            details = []
            for method, results in methods:
                counts = defaultdict(int)
                for result in results:
                    counts[result.category] += 1
                count_text = ", ".join(
                    f"{category}={counts[category]}" for category in sorted(counts)
                )
                details.append(f"`{method}` ({count_text})")
            lines.append(
                "| {} | {} | {} |".format(
                    SCHEMA_CATEGORY_TITLES[verdict],
                    len(methods),
                    "<br>".join(details) if details else "-",
                )
            )
        return lines

    def _markdown_null_result_summary(self):
        expected_null = []
        unexpected_null = []
        for result in self._all_results():
            expected = getattr(result, "expected", {})
            actual = getattr(result, "actual", {})
            if (
                "result" in expected
                and "result" in actual
                and expected.get("result") is None
                and actual.get("result") is None
            ):
                expected_null.append(result)
            elif (
                "result" in expected
                and "result" in actual
                and expected.get("result") is not None
                and actual.get("result") is None
            ):
                unexpected_null.append(result)

        lines = [
            "| Category | Cases | Details |",
            "| --- | ---: | --- |",
            "| expected `result: null` | {} | {} |".format(
                len(expected_null),
                ", ".join(f"`{result.spec_name}`" for result in expected_null) or "-",
            ),
            "| unexpected `result: null` | {} | {} |".format(
                len(unexpected_null),
                ", ".join(f"`{result.spec_name}`" for result in unexpected_null) or "-",
            ),
        ]
        return lines

    def _markdown_expected_failure_whitelist(self):
        lines = [
            (
                "These method-level lists document known gaps that are "
                "currently excluded from the schema test failure condition. "
                "Reduce these lists as methods are implemented or response "
                "schemas are fixed."
            ),
            "",
            "### Unimplemented RPC Methods",
            "",
        ]
        lines.extend(f"- `{method}`" for method in sorted(UNIMPLEMENTED_RPC_METHODS))
        lines.extend(
            [
                "",
                "### Schema Mismatch Whitelist",
                "",
                "| Category | RPC Methods |",
                "| --- | --- |",
            ]
        )
        for category in [
            "request_schema_wrong",
            "response_schema_wrong",
            "mixed_wrong",
        ]:
            methods = sorted(SCHEMA_MISMATCH_WHITELIST[category])
            lines.append(
                "| {} | {} |".format(
                    SCHEMA_CATEGORY_TITLES[category],
                    ", ".join(f"`{method}`" for method in methods) or "-",
                )
            )
        lines.extend(
            [
                "",
                "### Request Schema Case Whitelist",
                "",
                (
                    "These exact fixture cases are known Ethermint/Geth request "
                    "validation differences. They stay visible in the detailed "
                    "mismatch report but do not fail the schema test."
                ),
                "",
            ]
        )
        lines.extend(
            f"- `{spec_name}`"
            for spec_name in sorted(DECIMAL_BLOCK_NUMBER_REQUEST_SCHEMA_EXCEPTIONS)
        )
        return lines

    def _markdown_details(self):
        lines = []
        for attr in [
            "not_implemented",
            "request_schema_wrong",
            "response_schema_wrong",
        ]:
            results = getattr(self, attr)
            lines.extend([f"### {SCHEMA_CATEGORY_TITLES[attr]}", ""])
            if not results:
                lines.extend(["No cases.", ""])
                continue

            for result in results:
                lines.extend(
                    [
                        f"#### `{result.spec_name}`",
                        "",
                        f"- Method: `{result.method}`",
                        f"- Reason: {result.reason}",
                        f"- Comment: {result.comment or '-'}",
                        "",
                    ]
                )
                if result.category == "response_schema_wrong":
                    lines.extend(
                        [
                            "Schema differences:",
                            "",
                            "```text",
                            _format_schema_differences(
                                result.schema_expected, result.schema_actual
                            ),
                            "```",
                            "",
                        ]
                    )
                lines.extend(
                    [
                        "Request:",
                        "",
                        "```json",
                        _markdown_json(result.request),
                        "```",
                        "",
                        "Expected:",
                        "",
                        "```json",
                        _markdown_json(result.expected),
                        "```",
                        "",
                        "Actual:",
                        "",
                        "```json",
                        _markdown_json(result.actual),
                        "```",
                        "",
                    ]
                )
        return lines

    def _format_method_summary(self):
        by_method = defaultdict(list)
        for result in self._all_results():
            by_method[result.method].append(result)

        by_verdict = defaultdict(list)
        for method, results in sorted(by_method.items()):
            verdict = self._method_verdict(results)
            by_verdict[verdict].append((method, results))

        lines = ["", "ethermint RPC spec schema method summary (exclusive)"]
        for verdict in [
            "schema_correct",
            "not_implemented",
            "request_schema_wrong",
            "response_schema_wrong",
            "mixed_wrong",
        ]:
            methods = by_verdict.get(verdict, [])
            lines.append(f"- {SCHEMA_CATEGORY_TITLES[verdict]}: {len(methods)}")
            for method, results in methods:
                counts = defaultdict(int)
                for result in results:
                    counts[result.category] += 1
                details = ", ".join(
                    f"{category}={counts[category]}" for category in sorted(counts)
                )
                lines.append(f"  {method}: {details}")
        unexpected_null = [
            result
            for result in self._all_results()
            if "result" in getattr(result, "expected", {})
            and "result" in getattr(result, "actual", {})
            and getattr(result, "expected", {}).get("result") is not None
            and getattr(result, "actual", {}).get("result") is None
        ]
        lines.extend(
            [
                "",
                "ethermint RPC spec schema null-result summary",
                f"- unexpected result: null: {len(unexpected_null)}",
            ]
        )
        return lines

    def _all_results(self):
        return (
            self.schema_correct
            + self.not_implemented
            + self.request_schema_wrong
            + self.response_schema_wrong
        )

    @staticmethod
    def _method_verdict(results):
        # A method is "mixed_wrong" when its cases fall into more than one wrong
        # category (e.g., some cases have a wrong request schema and others a
        # wrong response schema), which signals an inconsistent implementation.
        categories = {result.category for result in results}
        if categories == {"schema_correct"}:
            return "schema_correct"
        if categories == {"not_implemented"}:
            return "not_implemented"

        wrong_categories = categories - {"schema_correct"}
        if len(wrong_categories) == 1:
            return next(iter(wrong_categories))
        return "mixed_wrong"

    def method_verdicts(self):
        by_method = defaultdict(list)
        for result in self._all_results():
            by_method[result.method].append(result)
        return {
            method: self._method_verdict(results)
            for method, results in by_method.items()
        }


def _format_method_set(methods):
    return ", ".join(f"`{method}`" for method in sorted(methods)) or "-"


def _is_decimal_block_number_request_schema_exception(result):
    if result.spec_name not in DECIMAL_BLOCK_NUMBER_REQUEST_SCHEMA_EXCEPTIONS:
        return False

    request = getattr(result, "request", {})
    params = request.get("params")
    if not isinstance(params, list) or not params:
        return False

    block_number = params[0]
    return (
        isinstance(block_number, str)
        and block_number.isascii()
        and block_number.isdecimal()
    )


def _is_whitelisted_schema_mismatch(result):
    return (
        result.category == "request_schema_wrong"
        and _is_decimal_block_number_request_schema_exception(result)
    )


def _method_verdicts_excluding_whitelisted_mismatches(summary):
    by_method = defaultdict(list)
    for result in summary._all_results():
        if not _is_whitelisted_schema_mismatch(result):
            by_method[result.method].append(result)

    return {
        method: RpcSpecSchemaSummary._method_verdict(results)
        for method, results in by_method.items()
    }


def _schema_mismatches(summary):
    mismatches = summary.request_schema_wrong + summary.response_schema_wrong
    return [
        f"{result.spec_name} ({result.method}): {result.reason}"
        for result in mismatches
        if not _is_whitelisted_schema_mismatch(result)
    ]


def _expected_failure_drift(summary):
    # Detects two types of staleness in the allow-lists:
    #   "unexpected" – a method now fails but is not listed → test gap
    #   "stale"      – a method is listed but now passes → list needs pruning
    verdicts = _method_verdicts_excluding_whitelisted_mismatches(summary)
    expected_by_verdict = {
        "not_implemented": UNIMPLEMENTED_RPC_METHODS,
        **SCHEMA_MISMATCH_WHITELIST,
    }
    actual_by_verdict = {
        verdict: {method for method, actual in verdicts.items() if actual == verdict}
        for verdict in expected_by_verdict
    }

    drift = []
    for verdict, expected_methods in expected_by_verdict.items():
        actual_methods = actual_by_verdict[verdict]
        unexpected = actual_methods - expected_methods
        stale = expected_methods - actual_methods
        if unexpected:
            drift.append(
                "{} has unlisted methods: {}".format(
                    SCHEMA_CATEGORY_TITLES[verdict],
                    _format_method_set(unexpected),
                )
            )
        if stale:
            drift.append(
                "{} whitelist has stale methods: {}".format(
                    SCHEMA_CATEGORY_TITLES[verdict],
                    _format_method_set(stale),
                )
            )

    allowed_wrong_verdicts = set(expected_by_verdict)
    unexpected_wrong_verdicts = {
        verdict
        for verdict in verdicts.values()
        if verdict != "schema_correct" and verdict not in allowed_wrong_verdicts
    }
    for verdict in sorted(unexpected_wrong_verdicts):
        methods = {method for method, actual in verdicts.items() if actual == verdict}
        drift.append(
            "{} has no whitelist: {}".format(
                SCHEMA_CATEGORY_TITLES[verdict],
                _format_method_set(methods),
            )
        )

    observed_decimal_block_number_cases = {
        result.spec_name
        for result in summary.request_schema_wrong
        if _is_decimal_block_number_request_schema_exception(result)
    }
    stale = (
        DECIMAL_BLOCK_NUMBER_REQUEST_SCHEMA_EXCEPTIONS
        - observed_decimal_block_number_cases
    )
    if stale:
        drift.append(
            "request schema case whitelist has stale cases: {}".format(
                ", ".join(f"`{spec_name}`" for spec_name in sorted(stale))
            )
        )
    return drift
